nginx:
  package: 'nginx'
  version: '1.8.0-1~trusty'
  conf:
    src_path: 'templates/nginx.conf.j2'
    vars:
      user: 'www-data'
      pid: '/var/run/nginx.pid'
      max_clients: 8096
      access_log: '/var/log/nginx/access.log'
      error_log: '/var/log/nginx/error.log'
  vhosts_conf: # list that contains {src_path, target_name}
    - src_path: 'templates/froide.nginx.conf.j2'
      target_name: "{{ application.deploy_name }}.conf"

uwsgi:
  package: 'uwsgi'
  version: '2.0.11.1'
  logs_path: '/var/log/uwsgi'
  apps_conf: # list that contains {src_path, target_name}
    - src_path: 'templates/froide.uwsgi.ini.j2'
      target_name: "{{ application.deploy_name }}.ini"
      envs: "{{ django_env }}"

supervisor:
  package: 'supervisor'
  version: '3.0b2'
  conf:
    src_path: 'templates/supervisord.conf.j2'
  logs_path: '/var/log/supervisord'
  apps_conf: # list that contains {src_path, target_name}
    - src_path: 'templates/froide.supervisor.conf.j2'
      target_name: "{{ application.deploy_name }}.conf"

rabbitmq:
  vhosts:
    - { 'name': 'froide'}
  users:
    - { 'username': 'froide', 'password': 'froide', vhost: 'froide'}

postgresql:
  version: '9.4'
  port: 5432
  admin:
    username: 'postgres'
  users:
    - name: froide
      password: froide
  databases:
    - name: froide_db
      owner: froide
      encoding: 'UTF-8'
      locale: 'en_US.UTF-8'
  user_privileges:
    - name: froide
      db: froide_db
      priv: "ALL"

django_env:
  DJANGO_CONFIGURATION: 'Vagrant'
  DJANGO_SETTINGS_MODULE: 'froide.settings'
  POSTMARK_INBOUND_ADDRESS: 'foi@example.com'
  POSTMARK_SMTP_SERVER: 'smtp.postmarkapp.com'
  POSTMARK_API_KEY: ''
  DATABASES: 'postgres://froide:froide@localhost:5432/froide_db'
  BROKER_URL: 'amqp://froide:froide@localhost:5672/froide'

env:
  http_proxy:
  https_proxy:
  ftp_proxy:

# application variables used in specific conf files
application:
  name: 'froide'
  hostname: 'froide.org'
  user: 'froide'
  group: 'froide'
  port: 50808
  deploy_name: 'froide_production'
  configuration: 'Vagrant'
  deploy:
    app_path: "{{ ad_deploy_to }}/app"
    venvs_path: "{{ ad_deploy_to }}/venvs"
    static_path: "{{ ad_deploy_to }}/app/current/public"

ad_deploy_from: "{{ lookup('env', 'FROIDE_DIR') }}"
ad_deploy_to: "/var/www/applications/froide_production"
ad_release_version: ""
ad_releases_to_keep: 2
ad_dependencies:
  - package: 'git'
    version: '1:1.9.1-1ubuntu0.1'
  - package: 'python2.7'
    version: '2.7.6-8'
  - package: 'python-pip'
    version: '1.5.4-1ubuntu3'
  - package: 'python-virtualenv'
    version: '1.11.4-1'
  - package: 'python-dev'
    version: '2.7.5-5ubuntu3'
